### ISSUE TITLE
a possible better pitch estimation than Yin 

### ISSUE THREAD

**Issue by francqz31** [ABSounds/YIN-Pitch#1]
@ABSounds hello how are you.

Have you seen this paper https://arxiv.org/abs/2306.09640 ? I think it beats all the current SOTA (including YIN,CREPE and HarmoF0)

Was wondering if you would consider implementing it if you are looking for the best Pitch estimation algo.

**Comment by tlr-id** [comment]
@francqz31 Hi !
Really interesting paper indeed ! Sadly I don't think that the authors released a Colab or a way to use their model yet. If you find one somewhere, I'm really interested.

In the current state of things, I don't think that @ABSounds is willing nor as the computational power to reproduce the model just based on the paper's description :/

**Comment by francqz31** [comment]
@tlr-id Thanks for your answer !

No problems I just thought that someone would be interested in implementing it , I will try to implement it myself but I would need someone to revise after me and evaluate it to check whether it is working correctly or not.

2-About the computational power I think they just trained it for 50 epochs on v100 or rtx 3090 or something .
in the 3.3. Training criteria section they said they followed similar training criterion as in [21] which is HarmoF0 and Harmof0 is trained for 50 epochs.

anyways thanks. :)

**Comment by ABSounds** [comment]
Hi! Exactly @tlr-id, @francqz31. The paper looks very promising but DNNs are a bit out of my comfort zone. Still, I will try to look into how an implementation of that model would work. If you try to implement it yourself either me or @tlr-id can take a look at it and check if it's working properly.

Best of luck!
